CYCLUS: cyclus::GenericResource Class Reference
cyclus::GenericResource Class Reference
A Generic Resource is a general type of resource in the Cyclus simulation, and is a catch-all for non-standard resources.
#include <generic_resource.h>
Public Types
typedef boost::shared_ptr
< GenericResource > Ptr
Public Member Functions
void Absorb (GenericResource::Ptr other)
Absorbs the contents of the given 'other' resource into this resource.
virtual Resource::Ptr Clone () const
Returns an untracked (not part of the simulation) copy of the resource.
GenericResource::Ptr Extract (double quantity)
Extracts the specified mass from this resource and returns it as a new generic resource object with the same quality/type.
virtual Resource::Ptr ExtractRes (double quantity)
Splits the resource and returns the extracted portion as a new resource object.
virtual const std::string & quality () const
Returns the quality of this resource (e.g. bananas, human labor, water, etc.).
virtual double quantity () const
Returns the quantity of this resource with dimensions as specified by the return value of units().
virtual void Record (Context *ctx) const
Records the resource's state to the output database.
virtual int state_id () const
Returns 0 (for now).
virtual const ResourceType type () const
Returns GenericResource::kType.
virtual std::string units () const
Returns the units this resource is based in (e.g. "kg").
Static Public Member Functions
static Ptr Create (Model *creator, double quantity, std::string quality, std::string units)
Creates a new generic resource that is "live" and tracked.
static Ptr CreateUntracked (double quantity, std::string quality, std::string units)
Creates a new generic resource that does not actually exist as part of the simulation and is untracked.
Static Public Attributes
static const ResourceType kType = "GenericResource"
Private Member Functions
GenericResource (Context *ctx, double quantity, std::string quality, std::string units)
Private Attributes
Context * ctx_
std::string quality_
double quantity_
ResTracker tracker_
std::string units_
Detailed Description
A Generic Resource is a general type of resource in the Cyclus simulation, and is a catch-all for non-standard resources.
It implements the Resource class interface in a simple way usable for things such as: bananas, man-hours, water, buying power, etc.
Definition at line 17 of file generic_resource.h.
Member Typedef Documentation
typedef boost::shared_ptr<GenericResource> cyclus::GenericResource::Ptr
Reimplemented from cyclus::Resource.
Definition at line 20 of file generic_resource.h.
Constructor & Destructor Documentation
cyclus::GenericResource::GenericResource (Context * ctx, double quantity, std::string quality, std::string units) [private]
Parameters:
ctx the simulation context
quantity is a double indicating the quantity
quality the resource quality
units is a string indicating the resource unit
Definition at line 71 of file generic_resource.cc.
Referenced by Clone(), Create(), CreateUntracked(), and Extract().
Member Function Documentation
void cyclus::GenericResource::Absorb (GenericResource::Ptr other)
Absorbs the contents of the given 'other' resource into this resource.
Exceptions:
ValueError 'other' resource is of different units and/or quality
Definition at line 41 of file generic_resource.cc.
References cyclus::ResTracker::Absorb(), quality(), quantity_, tracker_, and units().
Resource::Ptr cyclus::GenericResource::Clone () const [virtual]
Returns an untracked (not part of the simulation) copy of the resource.
A cloned resource should never record anything in the output database.
Implements cyclus::Resource.
Definition at line 33 of file generic_resource.cc.
References cyclus::ResTracker::DontTrack(), cyclus::units::g, GenericResource(), and tracker_.
GenericResource::Ptr cyclus::GenericResource::Create (Model * creator, double quantity, std::string quality, std::string units) [static]
Creates a new generic resource that is "live" and tracked.
creator is a pointer to the model creating the resource (usually will be the caller's "this" pointer). All future output data recorded will be done using the creator's context.
Definition at line 13 of file generic_resource.cc.
References cyclus::Model::context(), GenericResource(), quality(), quantity(), and units().
GenericResource::Ptr cyclus::GenericResource::CreateUntracked (double quantity, std::string quality, std::string units) [static]
Creates a new generic resource that does not actually exist as part of the simulation and is untracked.
Definition at line 24 of file generic_resource.cc.
References GenericResource().
GenericResource::Ptr cyclus::GenericResource::Extract (double quantity)
Extracts the specified mass from this resource and returns it as a new generic resource object with the same quality/type.
Exceptions:
ValueError tried to extract more than exists.
Definition at line 52 of file generic_resource.cc.
References ctx_, cyclus::ResTracker::Extract(), GenericResource(), quality_, quantity(), quantity_, tracker_, and units_.
Referenced by ExtractRes().
Resource::Ptr cyclus::GenericResource::ExtractRes (double quantity) [virtual]
Splits the resource and returns the extracted portion as a new resource object.
Allows for things like ResourceBuff and Traders to split offers/requests of arbitrary resource implementation type.
Returns:
a new resource object with same state id and quantity == quantity
Implements cyclus::Resource.
Definition at line 66 of file generic_resource.cc.
References Extract().
virtual const std::string& cyclus::GenericResource::quality () const [inline, virtual]
Returns the quality of this resource (e.g. bananas, human labor, water, etc.).
Definition at line 59 of file generic_resource.h.
References quality_.
Referenced by Absorb(), and Create().
virtual double cyclus::GenericResource::quantity () const [inline, virtual]
Returns the quantity of this resource with dimensions as specified by the return value of units().
Implements cyclus::Resource.
Definition at line 54 of file generic_resource.h.
References quantity_.
Referenced by Create(), and Extract().
virtual void cyclus::GenericResource::Record (Context * ctx) const [inline, virtual]
Records the resource's state to the output database.
This method should generally NOT record data accessible via the Resource class public methods (e.g. state_id, units, type, quantity).
Parameters:
ctx the simulation context used to record the data.
Implements cyclus::Resource.
Definition at line 48 of file generic_resource.h.
virtual int cyclus::GenericResource::state_id () const [inline, virtual]
Returns 0 (for now).
Implements cyclus::Resource.
Definition at line 36 of file generic_resource.h.
virtual const ResourceType cyclus::GenericResource::type () const [inline, virtual]
Returns GenericResource::kType.
Implements cyclus::Resource.
Definition at line 42 of file generic_resource.h.
References kType.
virtual std::string cyclus::GenericResource::units () const [inline, virtual]
Returns the units this resource is based in (e.g. "kg").
Implements cyclus::Resource.
Definition at line 50 of file generic_resource.h.
References units_.
Referenced by Absorb(), and Create().
Member Data Documentation
Context* cyclus::GenericResource::ctx_ [private]
Definition at line 83 of file generic_resource.h.
Referenced by Extract().
const ResourceType cyclus::GenericResource::kType = "GenericResource" [static]
Definition at line 21 of file generic_resource.h.
Referenced by type().
std::string cyclus::GenericResource::quality_ [private]
Definition at line 85 of file generic_resource.h.
Referenced by Extract(), and quality().
double cyclus::GenericResource::quantity_ [private]
Definition at line 86 of file generic_resource.h.
Referenced by Absorb(), Extract(), and quantity().
ResTracker cyclus::GenericResource::tracker_ [private]
Definition at line 87 of file generic_resource.h.
Referenced by Absorb(), Clone(), and Extract().
std::string cyclus::GenericResource::units_ [private]
Definition at line 84 of file generic_resource.h.
Referenced by Extract(), and units().
The documentation for this class was generated from the following files:
generic_resource.h
generic_resource.cc