CYCLUS: cyclus::Timer Class Reference
cyclus::Timer Class Reference
A timer to control a simulation with a one-month time step.
#include <timer.h>
Public Member Functions
int dur ()
Returns the duration of the simulation this Timer's timing.
void Initialize (Context *ctx, int dur=1, int m0=1, int y0=2010, int start=0, int decay=0, std::string handle="")
Initialize this Timer by setting the specs for the simulation.
void RegisterTickListener (TimeListener *agent)
registers a sim.
void Reset ()
reset all data (registered listeners, etc.) to empty or initial state
void RunSim (Context *ctx)
Runs the simulation.
int start_time ()
Returns the the start time of the simulation.
int time ()
Returns the current time, in months since the simulation started.
Timer ()
Private Member Functions
void LogTimeData (Context *ctx, std::string handle)
logs relevant time-related data with the output system, including: the simulation start time and the simulation duration
std::string ReportListeners ()
Returns a string of all models listening to the tick.
void SendTick ()
sends the tick signal to all of the models receiving time notifications.
void SendTock ()
sends the tock signal to all of the models receiving time notifications.
Private Attributes
int decay_interval_
time steps between automated global material decay driving
int dur_
The duration of this simulation, in months.
int month0_
The number of the month (Jan = 1, etc.) corresponding to t = 0 for the scenario being run.
std::vector< TimeListener * > new_tickers_
Concrete models that desire to receive tick and tock notifications.
int start_time_
The time at which the simulation started.
std::vector< TimeListener * > tick_listeners_
Concrete models that desire to receive tick and tock notifications.
int time_
The current time, measured in months from when the simulation started.
int year0_
The year corresponding to t = 0 for the scenario being run.
Detailed Description
A timer to control a simulation with a one-month time step.
The timer for a given simulation can be accessed via the simulation's Context.
Definition at line 20 of file timer.h.
Constructor & Destructor Documentation
cyclus::Timer::Timer ()
Definition at line 143 of file timer.cc.
Member Function Documentation
int cyclus::Timer::dur ()
Returns the duration of the simulation this Timer's timing.
Returns:
the duration, in months
Definition at line 138 of file timer.cc.
References dur_.
Referenced by Initialize(), and cyclus::Context::sim_dur().
void cyclus::Timer::Initialize (Context * ctx, int dur = 1, int m0 = 1, int y0 = 2010, int start = 0, int decay = 0, std::string handle = "")
Initialize this Timer by setting the specs for the simulation.
Parameters:
ctx the simulation context
dur the duration of this simulation, in months
m0 the month the simulation starts: Jan. = 1, ..., Dec. = 12 (default = 1)
y0 the year the simulation starts (default = 2010)
start the GENIUS time representing the first month of the simulation (default = 0)
decay interval between decay calculations in months. <=0 if decay is off (default = 0)
handle a user specified name for the simulation run
Definition at line 107 of file timer.cc.
References decay_interval_, dur(), dur_, LogTimeData(), month0_, start_time_, time_, and year0_.
Referenced by cyclus::Context::InitTime().
void cyclus::Timer::LogTimeData (Context * ctx, std::string handle) [private]
logs relevant time-related data with the output system, including: the simulation start time and the simulation duration
Definition at line 152 of file timer.cc.
References cyclus::Datum::AddVal(), decay_interval_, dur_, month0_, cyclus::Context::NewDatum(), cyclus::Datum::Record(), start_time_, and year0_.
Referenced by Initialize().
void cyclus::Timer::RegisterTickListener (TimeListener * agent)
registers a sim.
agent to receive time step notifications.
Parameters:
agent agent that will receive time-step notifications
Definition at line 84 of file timer.cc.
References CLOG, cyclus::Model::id(), cyclus::LEV_INFO2, cyclus::Model::name(), and new_tickers_.
Referenced by cyclus::Context::RegisterTimeListener().
std::string cyclus::Timer::ReportListeners () [private]
Returns a string of all models listening to the tick.
Definition at line 49 of file timer.cc.
References tick_listeners_.
Referenced by RunSim().
void cyclus::Timer::Reset ()
reset all data (registered listeners, etc.) to empty or initial state
Definition at line 95 of file timer.cc.
References decay_interval_, dur_, month0_, start_time_, tick_listeners_, time_, and year0_.
void cyclus::Timer::RunSim (Context * ctx)
Runs the simulation.
Definition at line 17 of file timer.cc.
References CLOG, decay_interval_, cyclus::Material::DecayAll(), dur_, cyclus::ExchangeManager< T >::Execute(), cyclus::LEV_DEBUG3, cyclus::LEV_INFO1, cyclus::LEV_INFO2, new_tickers_, ReportListeners(), SendTick(), SendTock(), start_time_, tick_listeners_, and time_.
void cyclus::Timer::SendTick () [private]
sends the tick signal to all of the models receiving time notifications.
Definition at line 60 of file timer.cc.
References CLOG, cyclus::LEV_INFO3, tick_listeners_, and time_.
Referenced by RunSim().
void cyclus::Timer::SendTock () [private]
sends the tock signal to all of the models receiving time notifications.
Definition at line 72 of file timer.cc.
References CLOG, cyclus::LEV_INFO3, tick_listeners_, and time_.
Referenced by RunSim().
int cyclus::Timer::start_time () [inline]
Returns the the start time of the simulation.
Definition at line 68 of file timer.h.
References start_time_.
Referenced by cyclus::Context::start_time().
int cyclus::Timer::time ()
Returns the current time, in months since the simulation started.
Returns:
the current time
Definition at line 91 of file timer.cc.
References time_.
Referenced by cyclus::Context::time().
Member Data Documentation
int cyclus::Timer::decay_interval_ [private]
time steps between automated global material decay driving
Definition at line 103 of file timer.h.
Referenced by Initialize(), LogTimeData(), Reset(), and RunSim().
int cyclus::Timer::dur_ [private]
The duration of this simulation, in months.
Definition at line 100 of file timer.h.
Referenced by dur(), Initialize(), LogTimeData(), Reset(), and RunSim().
int cyclus::Timer::month0_ [private]
The number of the month (Jan = 1, etc.) corresponding to t = 0 for the scenario being run.
Definition at line 109 of file timer.h.
Referenced by Initialize(), LogTimeData(), and Reset().
std::vector<TimeListener*> cyclus::Timer::new_tickers_ [private]
Concrete models that desire to receive tick and tock notifications.
Definition at line 124 of file timer.h.
Referenced by RegisterTickListener(), and RunSim().
int cyclus::Timer::start_time_ [private]
The time at which the simulation started.
Definition at line 95 of file timer.h.
Referenced by Initialize(), LogTimeData(), Reset(), RunSim(), and start_time().
std::vector<TimeListener*> cyclus::Timer::tick_listeners_ [private]
Concrete models that desire to receive tick and tock notifications.
Definition at line 119 of file timer.h.
Referenced by ReportListeners(), Reset(), RunSim(), SendTick(), and SendTock().
int cyclus::Timer::time_ [private]
The current time, measured in months from when the simulation started.
Definition at line 90 of file timer.h.
Referenced by Initialize(), Reset(), RunSim(), SendTick(), SendTock(), and time().
int cyclus::Timer::year0_ [private]
The year corresponding to t = 0 for the scenario being run.
Definition at line 114 of file timer.h.
Referenced by Initialize(), LogTimeData(), and Reset().
The documentation for this class was generated from the following files:
timer.h
timer.cc