CYCLUS: cyclus::FacilityModel Class Reference
cyclus::FacilityModel Class Reference
The FacilityModel class is the abstract class/interface used by all facility models.
#include <facility_model.h>
Public Member Functions
virtual bool CheckDecommissionCondition ()
facilities over write this method if a condition must be met before their destructors can be called
virtual void Decommission ()
decommissions the facility, default behavior is for the facility to delete itself
virtual void Deploy (Model *parent=NULL)
deploys the facility in the simulation
FacilityModel (Context *ctx)
virtual InstModel * FacInst ()
Returns this facility's institution.
virtual int FacLifetime ()
Returns the facility's lifetime.
virtual std::string FacName ()
Returns the facility's name.
virtual void InitFrom (QueryEngine *qe)
Initalize the FacilityModel from xml.
void InitFrom (FacilityModel *m)
Copy module members from a source model.
std::vector< std::string > InputCommodities ()
bool LifetimeReached (int time)
std::vector< std::string > OutputCommodities ()
virtual void SetFacLifetime (int lifetime)
Sets the facility's lifetime.
virtual void SetInstName (std::string name)
Sets this facility's instutution name.
virtual std::string str ()
every model should be able to print a verbose description
virtual void Tick (int time)=0
Each facility is prompted to do its beginning-of-time-step stuff at the tick of the timer.
virtual void Tock (int time)=0
Each facility is prompted to its end-of-time-step stuff on the tock of the timer.
virtual ~FacilityModel ()
Private Attributes
int fac_lifetime_
each facility needs a lifetime
std::vector< std::string > in_commods_
Most facilities will have a vector of incoming, request commodities.
std::string inst_name_
each facility should have an institution that manages it
std::vector< std::string > out_commods_
most facilities will have a vector of outgoing, offer commodities Ultimately, it's up to the facility to utilize this list.
Detailed Description
The FacilityModel class is the abstract class/interface used by all facility models.
This is all that is known externally about facilities
Introduction
The FacilityModel type plays a primary role in Cyclus. A FacilityModel facility is where offers and requests are generated and transmitted to a ResourceExchange and where shipments of material, issued by the exchange, are executed. The algorithms to determine what offers and requests are issued and how material shipments are handled are the primary differentiators between different FacilityModel implementations.
Like all model implementations, there are a number of implementations that are distributed as part of the core Cyclus application as well as implementations contributed by third-party developers. The links below describe additional parameters necessary for the complete definition of a facility of that implementation.
Available Core Implementations
SourceFacility: A facility that can produce a constant (or infinite) amount of some commodity
SinkFacility: A facility that can consume a constant (or infinite) amount of some commodity
NullFacility: A facility that consumes a constant amount of one commodity and produces a constant amount of another
Anticipated Core Implementations
Developers are encouraged to add to this list and create pages that describe the detailed behavior of these models.
RecipeReactor: A facility that consumes a fixed fresh fuel recipe one a time scale governed by reactor cycle lengths and batch sizes, and produced a fixed/corresponding spent fuel recipe at the same frequency - SeparationsMatrixFacility: A facility that consumes a fixed quantity of material of one commodity and produces many different output streams with the input isotopes distributed across those output streams according to a fixed matrix
EnrichmentFacility: A facility that offers a fixed quantity of SWUs to accomplish isotopic enrichment of material
Third-party Implementations
Collaborators are encouraged to add to this list and link to external pages that describe how to get the models and the detailed behavior
Definition at line 71 of file facility_model.h.
Constructor & Destructor Documentation
cyclus::FacilityModel::FacilityModel (Context * ctx)
Definition at line 19 of file facility_model.cc.
References cyclus::Model::model_type_.
cyclus::FacilityModel::~FacilityModel () [virtual]
Definition at line 28 of file facility_model.cc.
Member Function Documentation
bool cyclus::FacilityModel::CheckDecommissionCondition () [virtual]
facilities over write this method if a condition must be met before their destructors can be called
Definition at line 100 of file facility_model.cc.
Referenced by Decommission(), and cyclus::InstModel::Tock().
void cyclus::FacilityModel::Decommission () [virtual]
decommissions the facility, default behavior is for the facility to delete itself
Reimplemented from cyclus::Model.
Definition at line 90 of file facility_model.cc.
References CheckDecommissionCondition(), cyclus::Model::context(), cyclus::Model::name(), and cyclus::Context::UnregisterTrader().
Referenced by cyclus::InstModel::Tock().
void cyclus::FacilityModel::Deploy (Model * parent = NULL) [virtual]
deploys the facility in the simulation
Parameters:
parent the parent of this facility
Reimplemented from cyclus::Model.
Definition at line 69 of file facility_model.cc.
References cyclus::Model::context(), and cyclus::Context::RegisterTrader().
InstModel * cyclus::FacilityModel::FacInst () [virtual]
Returns this facility's institution.
Returns:
the institution assosicated with this facility
Definition at line 85 of file facility_model.cc.
References cyclus::Model::parent().
virtual int cyclus::FacilityModel::FacLifetime () [inline, virtual]
Returns the facility's lifetime.
Returns:
fac_lifetime_ the lifetime of this facility, an int, in
Definition at line 151 of file facility_model.h.
References fac_lifetime_.
Referenced by str().
virtual std::string cyclus::FacilityModel::FacName () [inline, virtual]
Returns the facility's name.
Returns:
fac_name_ the name of this facility, a string
Definition at line 121 of file facility_model.h.
References cyclus::Model::name().
void cyclus::FacilityModel::InitFrom (QueryEngine * qe) [virtual]
Initalize the FacilityModel from xml.
Calls the init function.
Parameters:
qe a pointer to a QueryEngine object containing intialization data
Reimplemented from cyclus::Model.
Definition at line 31 of file facility_model.cc.
References cyclus::Model::context(), cyclus::Model::id(), in_commods_, cyclus::LEV_DEBUG2, LOG, out_commods_, SetFacLifetime(), and cyclus::Context::sim_dur().
Referenced by InitFrom().
void cyclus::FacilityModel::InitFrom (FacilityModel * m)
Copy module members from a source model.
Any facility subclassing facility model should invoke their own InitFrom method, calling FacilityModel's first!
Parameters:
m the model to copy from
Definition at line 60 of file facility_model.cc.
References fac_lifetime_, in_commods_, InitFrom(), inst_name_, and out_commods_.
std::vector< std::string > cyclus::FacilityModel::InputCommodities ()
Returns:
the input commodities
Definition at line 105 of file facility_model.cc.
References in_commods_.
bool cyclus::FacilityModel::LifetimeReached (int time)
Parameters:
time the time used to query whether it is past the facility's decommission date
Returns:
true if the time is greater than the decommission date
Definition at line 115 of file facility_model.cc.
References cyclus::Model::birthtime(), and fac_lifetime_.
Referenced by cyclus::InstModel::Tock().
std::vector< std::string > cyclus::FacilityModel::OutputCommodities ()
Returns:
the output commodities
Definition at line 110 of file facility_model.cc.
References out_commods_.
virtual void cyclus::FacilityModel::SetFacLifetime (int lifetime) [inline, virtual]
Sets the facility's lifetime.
Parameters:
lifetime is the new lifetime of the facility in months
Definition at line 143 of file facility_model.h.
References fac_lifetime_.
Referenced by InitFrom().
virtual void cyclus::FacilityModel::SetInstName (std::string name) [inline, virtual]
Sets this facility's instutution name.
Parameters:
name the name of the institution associated with this
Definition at line 129 of file facility_model.h.
References inst_name_, and cyclus::Model::name().
std::string cyclus::FacilityModel::str () [virtual]
every model should be able to print a verbose description
Reimplemented from cyclus::Model.
Definition at line 75 of file facility_model.cc.
References cyclus::Model::birthtime(), fac_lifetime_, and FacLifetime().
virtual void cyclus::FacilityModel::Tick (int time) [pure virtual]
Each facility is prompted to do its beginning-of-time-step stuff at the tick of the timer.
Parameters:
time is the time to perform the tick
Implements cyclus::TimeListener.
virtual void cyclus::FacilityModel::Tock (int time) [pure virtual]
Each facility is prompted to its end-of-time-step stuff on the tock of the timer.
By default, facilities are decommissioned if time is greater than or equal to its end date.
Parameters:
time is the time to perform the tock
Implements cyclus::TimeListener.
Referenced by cyclus::InstModel::Tock().
Member Data Documentation
int cyclus::FacilityModel::fac_lifetime_ [private]
each facility needs a lifetime
Definition at line 216 of file facility_model.h.
Referenced by FacLifetime(), InitFrom(), LifetimeReached(), SetFacLifetime(), and str().
std::vector<std::string> cyclus::FacilityModel::in_commods_ [private]
Most facilities will have a vector of incoming, request commodities.
Ultimately, it's up to the facility to utilize this list. However, the user interface is assisted by this specificity in the input scheme. For details, see issue #323 in cyclus/cyclus.
Definition at line 203 of file facility_model.h.
Referenced by InitFrom(), and InputCommodities().
std::string cyclus::FacilityModel::inst_name_ [private]
each facility should have an institution that manages it
Definition at line 195 of file facility_model.h.
Referenced by InitFrom(), and SetInstName().
std::vector<std::string> cyclus::FacilityModel::out_commods_ [private]
most facilities will have a vector of outgoing, offer commodities Ultimately, it's up to the facility to utilize this list.
However, the user interface is assisted by this specificity in the input scheme. For details, see issue #323 in cyclus/cyclus.
Definition at line 211 of file facility_model.h.
Referenced by InitFrom(), and OutputCommodities().
The documentation for this class was generated from the following files:
facility_model.h
facility_model.cc