CYCLUS: cyclus::Decayer Class Reference
cyclus::Decayer Class Reference
#include <decayer.h>
Public Member Functions
void Decay (double years)
decay the material
Decayer (const CompMap &comp)
default constructor
void GetResult (CompMap &comp)
set the composition from a CompMap
int n_tracked_isotopes ()
the number of tracked isotopes
int TrackedIsotope (int i)
the tracked isotope at position i
Static Public Member Functions
static double DecayConstant (int iso)
Returns the decay constant for specified isotope in inverse years.
Static Private Member Functions
static void AddIsoToList (int iso)
Add the Isotope to our list of tracked isotopes IFF it is not.
static void BuildDecayMatrix ()
Builds the decay matrix needed for the decay calculations from the parent and daughters map variables.
static void LoadDecayInfo ()
Reads the decay information found in the 'decayInfo.dat' file into the parent and daughters maps.Uses these maps to create the.
Private Attributes
Vector post_vect_
Vector pre_vect_
The atomic composition map.
Static Private Attributes
static DaughtersMap daughters_ = DaughtersMap()
The CompMap's daughters.
static bool decay_info_loaded_ = false
whether the decay information is loaded
static Matrix decay_matrix_ = Matrix()
The decay matrix.
static IsoList isotopes_tracked_ = IsoList()
the list of tracked isotopes
static ParentMap parent_ = ParentMap()
The CompMap's parent.
Detailed Description
Definition at line 31 of file decayer.h.
Constructor & Destructor Documentation
cyclus::Decayer::Decayer (const CompMap & comp)
default constructor
Definition at line 21 of file decayer.cc.
References cyclus::LMatrix::AddRow(), daughters_, decay_info_loaded_, LoadDecayInfo(), parent_, and pre_vect_.
Member Function Documentation
void cyclus::Decayer::AddIsoToList (int iso) [static, private]
Add the Isotope to our list of tracked isotopes IFF it is not.
Definition at line 129 of file decayer.cc.
References isotopes_tracked_.
Referenced by LoadDecayInfo().
void cyclus::Decayer::BuildDecayMatrix () [static, private]
Builds the decay matrix needed for the decay calculations from the parent and daughters map variables.
The resulting matrix is stored in the static variable decayMatrix.
Definition at line 161 of file decayer.cc.
References daughters_, decay_matrix_, and parent_.
Referenced by LoadDecayInfo().
void cyclus::Decayer::Decay (double years)
decay the material
Parameters:
years the number of years to decay
Definition at line 197 of file decayer.cc.
References decay_matrix_, cyclus::UniformTaylor::MatrixExpSolver(), post_vect_, and pre_vect_.
Referenced by cyclus::Composition::NewDecay().
double cyclus::Decayer::DecayConstant (int iso) [static]
Returns the decay constant for specified isotope in inverse years.
Definition at line 117 of file decayer.cc.
References decay_info_loaded_, LoadDecayInfo(), and parent_.
Referenced by cyclus::Material::Decay().
void cyclus::Decayer::GetResult (CompMap & comp)
set the composition from a CompMap
Definition at line 138 of file decayer.cc.
References cyclus::LEV_ERROR, LOG, cyclus::LMatrix::NumRows(), parent_, and post_vect_.
Referenced by cyclus::Composition::NewDecay().
void cyclus::Decayer::LoadDecayInfo () [static, private]
Reads the decay information found in the 'decayInfo.dat' file into the parent and daughters maps.Uses these maps to create the.
Definition at line 54 of file decayer.cc.
References AddIsoToList(), BuildDecayMatrix(), daughters_, cyclus::Env::GetBuildPath(), and parent_.
Referenced by DecayConstant(), and Decayer().
int cyclus::Decayer::n_tracked_isotopes () [inline]
the number of tracked isotopes
Definition at line 105 of file decayer.h.
References isotopes_tracked_.
int cyclus::Decayer::TrackedIsotope (int i) [inline]
the tracked isotope at position i
Definition at line 112 of file decayer.h.
References isotopes_tracked_.
Member Data Documentation
DaughtersMap cyclus::Decayer::daughters_ = DaughtersMap() [static, private]
The CompMap's daughters.
Definition at line 54 of file decayer.h.
Referenced by BuildDecayMatrix(), Decayer(), and LoadDecayInfo().
bool cyclus::Decayer::decay_info_loaded_ = false [static, private]
whether the decay information is loaded
Definition at line 70 of file decayer.h.
Referenced by DecayConstant(), and Decayer().
Matrix cyclus::Decayer::decay_matrix_ = Matrix() [static, private]
The decay matrix.
Definition at line 59 of file decayer.h.
Referenced by BuildDecayMatrix(), and Decay().
IsoList cyclus::Decayer::isotopes_tracked_ = IsoList() [static, private]
the list of tracked isotopes
Definition at line 75 of file decayer.h.
Referenced by AddIsoToList(), n_tracked_isotopes(), and TrackedIsotope().
ParentMap cyclus::Decayer::parent_ = ParentMap() [static, private]
The CompMap's parent.
Definition at line 49 of file decayer.h.
Referenced by BuildDecayMatrix(), DecayConstant(), Decayer(), GetResult(), and LoadDecayInfo().
Vector cyclus::Decayer::post_vect_ [private]
Definition at line 65 of file decayer.h.
Referenced by Decay(), and GetResult().
Vector cyclus::Decayer::pre_vect_ [private]
The atomic composition map.
Definition at line 64 of file decayer.h.
Referenced by Decay(), and Decayer().
The documentation for this class was generated from the following files:
decayer.h
decayer.cc