CYCLUS: cyclus::XMLFileLoader Class Reference
cyclus::XMLFileLoader Class Reference
a class that encapsulates the methods needed to load input to a cyclus simulation from xml
#include <xml_file_loader.h>
Public Member Functions
void ApplySchema (const std::stringstream &schema)
applies a schema agaisnt the parser used by the file loader
void LoadControlParams ()
Method to load the simulation control parameters.
void LoadRecipes ()
Method to load recipes from either the primary input file or a recipeBook catalog.
virtual void LoadSim ()
Load an entire simulation from the inputfile.
void LoadSolver ()
Method to load the simulation exchange solver.
void ProcessCommodities (std::map< std::string, double > *commodity_order)
Processes commodity orders, such that any without a defined order (i.e., are nonpositive), are given an order value greater the last known commodity.
XMLFileLoader (Context *ctx, std::string schema_path, const std::string load_filename="")
Constructor to create a new XML for loading.
virtual ~XMLFileLoader ()
Protected Member Functions
void LoadDynamicModules ()
Method to load all dyamic modules.
virtual void LoadInitialAgents ()
Creates all initial agent instances from the input file.
void LoadRecipe (QueryEngine *qe)
loads a specific recipe
virtual std::string master_schema ()
Protected Attributes
Context * ctx_
std::string file_
the input file name
std::map< std::string,
DynamicModule * > modules_
a map of loaded modules.
boost::shared_ptr< XMLParser > parser_
the parser
std::string schema_path_
filepath to the schema
std::map< std::string,
std::string > schema_paths_
a map of module types to their paths in xml
Detailed Description
a class that encapsulates the methods needed to load input to a cyclus simulation from xml
Definition at line 32 of file xml_file_loader.h.
Constructor & Destructor Documentation
cyclus::XMLFileLoader::XMLFileLoader (Context * ctx, std::string schema_path, const std::string load_filename = "")
Constructor to create a new XML for loading.
Defaults to using the main schema.
Parameters:
ctx all input file configuration will be loaded into here
load_filename The filename for the file to be loaded; defaults to an empty string
Definition at line 109 of file xml_file_loader.cc.
References cyclus::Datum::AddVal(), ctx_, file_, cyclus::LoadStringstreamFromFile(), cyclus::Context::NewDatum(), parser_, cyclus::Datum::Record(), schema_path_, and schema_paths_.
cyclus::XMLFileLoader::~XMLFileLoader () [virtual]
Definition at line 129 of file xml_file_loader.cc.
References modules_.
Member Function Documentation
void cyclus::XMLFileLoader::ApplySchema (const std::stringstream & schema)
applies a schema agaisnt the parser used by the file loader
Parameters:
schema the schema representation
Definition at line 138 of file xml_file_loader.cc.
References parser_.
void cyclus::XMLFileLoader::LoadControlParams ()
Method to load the simulation control parameters.
Definition at line 277 of file xml_file_loader.cc.
References ctx_, cyclus::QueryEngine::GetElementContent(), cyclus::Context::InitTime(), cyclus::QueryEngine::NElementsMatchingQuery(), parser_, and cyclus::QueryEngine::QueryElement().
Referenced by LoadSim().
void cyclus::XMLFileLoader::LoadDynamicModules () [protected]
Method to load all dyamic modules.
Definition at line 266 of file xml_file_loader.cc.
References CLOG, cyclus::LEV_DEBUG1, cyclus::Env::ListModules(), and modules_.
Referenced by LoadSim().
void cyclus::XMLFileLoader::LoadInitialAgents () [protected, virtual]
Creates all initial agent instances from the input file.
Reimplemented in cyclus::XMLFlatLoader.
Definition at line 232 of file xml_file_loader.cc.
References cyclus::Context::AddPrototype(), CLOG, ctx_, cyclus::Model::Deploy(), cyclus::QueryEngine::GetElementName(), cyclus::Model::id(), cyclus::Model::InitFrom(), cyclus::LEV_DEBUG3, cyclus::Model::model_type(), cyclus::Model::ModelImpl(), modules_, cyclus::Model::name(), cyclus::XMLQueryEngine::NElementsMatchingQuery(), parser_, cyclus::QueryEngine::QueryElement(), schema_paths_, and cyclus::Model::SetModelImpl().
Referenced by LoadSim().
void cyclus::XMLFileLoader::LoadRecipe (QueryEngine * qe) [protected]
loads a specific recipe
void cyclus::XMLFileLoader::LoadRecipes ()
Method to load recipes from either the primary input file or a recipeBook catalog.
Definition at line 218 of file xml_file_loader.cc.
References cyclus::Context::AddRecipe(), CLOG, ctx_, cyclus::QueryEngine::GetElementContent(), cyclus::LEV_DEBUG3, cyclus::XMLQueryEngine::NElementsMatchingQuery(), parser_, cyclus::QueryEngine::QueryElement(), and cyclus::ReadRecipe().
Referenced by LoadSim().
void cyclus::XMLFileLoader::LoadSim () [virtual]
Load an entire simulation from the inputfile.
Parameters:
use_flat_schema whether or not to use the flat schema
Definition at line 148 of file xml_file_loader.cc.
References LoadControlParams(), LoadDynamicModules(), LoadInitialAgents(), LoadRecipes(), LoadSolver(), master_schema(), and parser_.
void cyclus::XMLFileLoader::LoadSolver ()
Method to load the simulation exchange solver.
Definition at line 165 of file xml_file_loader.cc.
References ctx_, cyclus::QueryEngine::GetElementContent(), cyclus::XMLQueryEngine::NElementsMatchingQuery(), parser_, ProcessCommodities(), cyclus::QueryEngine::QueryElement(), cyclus::GreedyPreconditioner::REVERSE, and cyclus::Context::solver().
Referenced by LoadSim().
std::string cyclus::XMLFileLoader::master_schema () [protected, virtual]
Reimplemented in cyclus::XMLFlatLoader.
Definition at line 143 of file xml_file_loader.cc.
References cyclus::BuildMasterSchema(), and schema_path_.
Referenced by LoadSim().
void cyclus::XMLFileLoader::ProcessCommodities (std::map< std::string, double > * commodity_order)
Processes commodity orders, such that any without a defined order (i.e., are nonpositive), are given an order value greater the last known commodity.
Definition at line 195 of file xml_file_loader.cc.
References CLOG, and cyclus::LEV_INFO1.
Referenced by LoadSolver().
Member Data Documentation
Context* cyclus::XMLFileLoader::ctx_ [protected]
Definition at line 73 of file xml_file_loader.h.
Referenced by LoadControlParams(), cyclus::XMLFlatLoader::LoadInitialAgents(), LoadInitialAgents(), LoadRecipes(), LoadSolver(), and XMLFileLoader().
std::string cyclus::XMLFileLoader::file_ [protected]
the input file name
Definition at line 95 of file xml_file_loader.h.
Referenced by XMLFileLoader().
std::map< std::string, DynamicModule*> cyclus::XMLFileLoader::modules_ [protected]
a map of loaded modules.
all dynamically loaded modules are registered with this map when loaded.
Definition at line 86 of file xml_file_loader.h.
Referenced by LoadDynamicModules(), cyclus::XMLFlatLoader::LoadInitialAgents(), LoadInitialAgents(), and ~XMLFileLoader().
boost::shared_ptr<XMLParser> cyclus::XMLFileLoader::parser_ [protected]
the parser
Definition at line 82 of file xml_file_loader.h.
Referenced by ApplySchema(), LoadControlParams(), cyclus::XMLFlatLoader::LoadInitialAgents(), LoadInitialAgents(), LoadRecipes(), LoadSim(), LoadSolver(), and XMLFileLoader().
std::string cyclus::XMLFileLoader::schema_path_ [protected]
filepath to the schema
Definition at line 76 of file xml_file_loader.h.
Referenced by cyclus::XMLFlatLoader::master_schema(), master_schema(), and XMLFileLoader().
std::map<std::string, std::string> cyclus::XMLFileLoader::schema_paths_ [protected]
a map of module types to their paths in xml
Definition at line 79 of file xml_file_loader.h.
Referenced by LoadInitialAgents(), and XMLFileLoader().
The documentation for this class was generated from the following files:
xml_file_loader.h
xml_file_loader.cc