CYCLUS: cyclus::RegionModel Class Reference
cyclus::RegionModel Class Reference
The RegionModel class is the abstract class/interface used by all region models.
#include <region_model.h>
Public Member Functions
virtual void Deploy (Model *parent)
perform actions required when entering the simulation
virtual void InitFrom (QueryEngine *qe)
Initalize the InstModel from a QueryEngine.
bool IsAllowedFacility (std::string proto_name)
returns if the facility is in this region's allowed facs
RegionModel (Context *ctx)
Default constructor for RegionModel Class.
virtual std::string str ()
every model should be able to print a verbose description
virtual void Tick (int time)
Each region is prompted to do its beginning-of-time-step stuff at the tick of the timer.
virtual void Tock (int time)
Each region is prompted to do its end-of-time-step stuff at the tock of the timer.
virtual ~RegionModel ()
RegionModels should not be indestructible.
Protected Member Functions
virtual void AddChildrenToTree ()
populate the region's list of child institutions
virtual void AddRegionAsRootNode ()
set the parameters necessary for RegionModel to interact with the simulation
virtual void InitAllowedFacilities (QueryEngine *qe)
populate the region's list of allowed facilities
void InitFrom (RegionModel *m)
virtual void InitInstitutionNames (QueryEngine *qe)
populate the region's list of institution names
Private Attributes
std::set< std::string > allowedFacilities_
every region has a list of allowed facilities
std::set< std::string > inst_names_
the names of the institutions in this region
Detailed Description
The RegionModel class is the abstract class/interface used by all region models.
This is all that is known externally about Regions
Introduction
The RegionModel type assists in defining the region-institution-facility hierarchy in Cyclus. A RegionModel region is an actor associated with a set of institutions or facilities for which it is responsible. A RegionModel may be used to adjust preferences in the ResourceExchange to make material routing decisions based on interfacility relationships. Deployment is a primary differentiator between different RegionModel implementations.
Like all model implementations, there are a number of implementations that are distributed as part of the core Cyclus application as well as implementations contributed by third-party developers. The links below describe additional parameters necessary for the complete definition of a region of that implementation.
Basic Functionality
All regions perform three major functions:
Schedule the deployment of facilities by either
Determining when new facilities need to be built, or
Deferring to an InstModel to make this determination.
Manage the deployment of facilities by interacting with the Institutions to select a specific facility type and facility parameters
Different regional types will be required to fully define the first two functions while the third is a built-in capability for all region types. For instance, one may wish to include a region which has exponential growth as its driving factor for facility creation or one may wish to have pre-determined building order based on time step (e.g. the JAEA benchmark). Additionally, one may wish for there to be a one-to-one region-to-instituion deployment for simple models and thus demand that each instiution simply build a facility when its region determines the facility's necessity. However, one may instead wish to have two competing instiutions in one region and have the institution which provides the best incentive to the region to build a required facility.
Available Core Implementations
NullRegion: This region is associated with a set of allowed facilities. It defers to an institution regarding facility deployment, making no demands on facility type or parameter (save the facility's allowability in the region). It makes no alterations to messages passed through it in either the up or down direction.
Definition at line 63 of file region_model.h.
Constructor & Destructor Documentation
cyclus::RegionModel::RegionModel (Context * ctx)
Default constructor for RegionModel Class.
Definition at line 26 of file region_model.cc.
References cyclus::Model::model_type_.
virtual cyclus::RegionModel::~RegionModel () [inline, virtual]
RegionModels should not be indestructible.
Definition at line 77 of file region_model.h.
Member Function Documentation
void cyclus::RegionModel::AddChildrenToTree () [protected, virtual]
populate the region's list of child institutions
Definition at line 71 of file region_model.cc.
References cyclus::Model::context(), cyclus::Context::CreateModel(), cyclus::Model::Deploy(), and inst_names_.
Referenced by Deploy().
void cyclus::RegionModel::AddRegionAsRootNode () [protected, virtual]
set the parameters necessary for RegionModel to interact with the simulation
Definition at line 66 of file region_model.cc.
References cyclus::Model::context(), and cyclus::Context::RegisterTimeListener().
Referenced by Deploy().
void cyclus::RegionModel::Deploy (Model * parent) [virtual]
perform actions required when entering the simulation
Reimplemented from cyclus::Model.
Definition at line 59 of file region_model.cc.
References AddChildrenToTree(), and AddRegionAsRootNode().
void cyclus::RegionModel::InitAllowedFacilities (QueryEngine * qe) [protected, virtual]
populate the region's list of allowed facilities
Definition at line 38 of file region_model.cc.
References allowedFacilities_, cyclus::QueryEngine::GetElementContent(), and cyclus::QueryEngine::NElementsMatchingQuery().
Referenced by InitFrom().
void cyclus::RegionModel::InitFrom (QueryEngine * qe) [virtual]
Initalize the InstModel from a QueryEngine.
Calls the init function.
Parameters:
qe A pointer to a QueryEngine object containing initialization data
Reimplemented from cyclus::Model.
Definition at line 31 of file region_model.cc.
References InitAllowedFacilities(), and InitInstitutionNames().
Referenced by InitFrom().
void cyclus::RegionModel::InitFrom (RegionModel * m) [protected]
Definition at line 19 of file region_model.cc.
References allowedFacilities_, InitFrom(), and inst_names_.
void cyclus::RegionModel::InitInstitutionNames (QueryEngine * qe) [protected, virtual]
populate the region's list of institution names
Definition at line 48 of file region_model.cc.
References cyclus::QueryEngine::GetElementContent(), inst_names_, cyclus::Model::name(), cyclus::QueryEngine::NElementsMatchingQuery(), and cyclus::QueryEngine::QueryElement().
Referenced by InitFrom().
bool cyclus::RegionModel::IsAllowedFacility (std::string proto_name) [inline]
returns if the facility is in this region's allowed facs
Definition at line 121 of file region_model.h.
References allowedFacilities_.
std::string cyclus::RegionModel::str () [virtual]
every model should be able to print a verbose description
Reimplemented from cyclus::Model.
Definition at line 81 of file region_model.cc.
References allowedFacilities_, and cyclus::Model::children().
void cyclus::RegionModel::Tick (int time) [virtual]
Each region is prompted to do its beginning-of-time-step stuff at the tick of the timer.
The default behavior is to ignore the tick.
Parameters:
time is the time to perform the tick
Implements cyclus::TimeListener.
Definition at line 105 of file region_model.cc.
References cyclus::Model::children().
void cyclus::RegionModel::Tock (int time) [virtual]
Each region is prompted to do its end-of-time-step stuff at the tock of the timer.
The default behavior is to ignore the tock.
Parameters:
time is the time to perform the tock
Implements cyclus::TimeListener.
Definition at line 121 of file region_model.cc.
References cyclus::Model::children().
Member Data Documentation
std::set<std::string> cyclus::RegionModel::allowedFacilities_ [private]
every region has a list of allowed facilities
Definition at line 154 of file region_model.h.
Referenced by InitAllowedFacilities(), InitFrom(), IsAllowedFacility(), and str().
std::set<std::string> cyclus::RegionModel::inst_names_ [private]
the names of the institutions in this region
Definition at line 159 of file region_model.h.
Referenced by AddChildrenToTree(), InitFrom(), and InitInstitutionNames().
The documentation for this class was generated from the following files:
region_model.h
region_model.cc