CYCLUS: cyclus::Model Class Reference
cyclus::Model Class Reference
#include <model.h>
Public Member Functions
virtual void AdjustGenRsrcPrefs (PrefMap< GenericResource >::type &prefs)
default implementation for material preferences.
virtual void AdjustMatlPrefs (PrefMap< Material >::type &prefs)
default implementation for material preferences.
const int birthtime () const
returns the time this model began operation (-1 if the model has never been deployed).
Model * children (int i)
returns the ith child
const std::vector< Model * > & children () const
returns a list of children this model has
virtual Model * Clone ()=0
Return a newly created/allocated prototype that is an exact copy of this.
Context * context () const
Returns this model's current simulation context.
const int deathtime () const
returns the time this model ceased operation (-1 if the model is still operating).
virtual void Decommission ()
Decommissions the model, removing it from the simulation.
virtual void Deploy (Model *parent=NULL)
creates the parent-child link and invokes the core-level and module-level enter simulation methods
std::vector< std::string > GetTreePrintOuts (Model *m)
returns a vector of strings representing the parent-child tree at the node for Model m
const int id () const
get model instance ID
virtual void InitFrom (QueryEngine *qe)
Initializes a model by reading parameters from the passed QueryEngine.
Model (Context *ctx)
Constructor for the Model Class.
const std::string model_type () const
returns a string that describes the model subclass (e.g. Region, etc.)
const std::string ModelImpl ()
get model implementation name
const std::string name () const
get model instance name
Model * parent () const
returns parent of this model
const int parent_id () const
returns the parent's id
std::string PrintChildren ()
recursively prints the parent-child tree
virtual std::string schema ()
Returns a module's xml rng schema for initializing from input files.
void SetModelImpl (std::string new_impl)
set model implementation
virtual std::string str ()
every model should be able to print a verbose description
virtual ~Model ()
Recursively destructs all children and removes references to self form parent.
Protected Member Functions
virtual std::string InformErrorMsg (std::string msg)
adds model-specific information prefix to an error message
void InitFrom (Model *m)
Initializes a model by copying parameters from the passed model m.
Protected Attributes
std::string model_type_
describes the model subclass (e.g.
Private Member Functions
void AddToTable ()
add an agent to the transactiont table
Private Attributes
int birthtime_
born on date of this model
std::vector< Model * > children_
children of this model
Context * ctx_
int deathtime_
died on date of this model
int id_
an instance-unique ID for the model
std::string model_impl_
concrete type of a model (e.g. "MyReactorModel")
std::string name_
every instance of a model should have a name
Model * parent_
parent of this model
int parent_id_
parent's ID of this model Note: we keep the parent id in the model so we can reference it even if the parent is deallocated.
Static Private Attributes
static int next_id_ = 0
Stores the next available facility ID.
Detailed Description
Description
The Model class is the abstract class used by all types of models that will be available for dynamic loading. This common interface means that the basic process of loading and registering models can be implemented in a single place.
Definition at line 40 of file model.h.
Constructor & Destructor Documentation
cyclus::Model::Model (Context * ctx)
Constructor for the Model Class.
Warning:
all constructors must set id_ and increment next_id_
Definition at line 47 of file model.cc.
References ctx_, id_, cyclus::LEV_DEBUG3, MLOG, and cyclus::Context::model_list_.
cyclus::Model::~Model () [virtual]
Recursively destructs all children and removes references to self form parent.
Definition at line 61 of file model.cc.
References cyclus::Datum::AddVal(), birthtime_, children_, CLOG, context(), ctx_, deathtime_, cyclus::Context::DelModel(), id(), id_, cyclus::LEV_DEBUG2, cyclus::LEV_DEBUG3, cyclus::LEV_DEBUG4, MLOG, cyclus::Context::model_list_, name(), cyclus::Context::NewDatum(), parent_, cyclus::Datum::Record(), and cyclus::Context::time().
Member Function Documentation
void cyclus::Model::AddToTable () [private]
add an agent to the transactiont table
Definition at line 173 of file model.cc.
References cyclus::Datum::AddVal(), birthtime(), ctx_, model_type(), ModelImpl(), name(), cyclus::Context::NewDatum(), parent_id_, and cyclus::Datum::Record().
Referenced by Deploy().
virtual void cyclus::Model::AdjustGenRsrcPrefs (PrefMap< GenericResource >::type & prefs) [inline, virtual]
default implementation for material preferences.
Definition at line 135 of file model.h.
Referenced by cyclus::AdjustPrefs().
virtual void cyclus::Model::AdjustMatlPrefs (PrefMap< Material >::type & prefs) [inline, virtual]
default implementation for material preferences.
Definition at line 132 of file model.h.
Referenced by cyclus::AdjustPrefs().
const int cyclus::Model::birthtime () const [inline]
returns the time this model began operation (-1 if the model has never been deployed).
Definition at line 171 of file model.h.
References birthtime_.
Referenced by AddToTable(), cyclus::FacilityModel::LifetimeReached(), and cyclus::FacilityModel::str().
Model* cyclus::Model::children (int i) [inline]
returns the ith child
Definition at line 127 of file model.h.
References children_.
Referenced by GetTreePrintOuts().
const std::vector<Model*>& cyclus::Model::children () const [inline]
returns a list of children this model has
Definition at line 178 of file model.h.
References children_.
Referenced by cyclus::InstModel::GetNumFacilities(), cyclus::RegionModel::str(), cyclus::InstModel::Tick(), cyclus::RegionModel::Tick(), cyclus::InstModel::Tock(), and cyclus::RegionModel::Tock().
virtual Model* cyclus::Model::Clone () [pure virtual]
Return a newly created/allocated prototype that is an exact copy of this.
All initialization and state cloning operations should be done in the model's InitFrom method. The new model instance should generally NOT be created using a default copy-constructor.
Example:
 class MyModelClass : virtual public Model {
   ...
   virtual Model* Clone() {
     MyModelClass* m = new MyModelClass(context());
     m->InitFrom(this);
     return m;
   };
   ...
 };
Referenced by cyclus::Context::CreateModel().
Context* cyclus::Model::context () const [inline]
Returns this model's current simulation context.
Definition at line 158 of file model.h.
References ctx_.
Referenced by cyclus::RegionModel::AddChildrenToTree(), cyclus::RegionModel::AddRegionAsRootNode(), cyclus::InstModel::Build(), cyclus::GenericResource::Create(), cyclus::Material::Create(), cyclus::FacilityModel::Decommission(), cyclus::FacilityModel::Deploy(), InformErrorMsg(), cyclus::FacilityModel::InitFrom(), and ~Model().
const int cyclus::Model::deathtime () const [inline]
returns the time this model ceased operation (-1 if the model is still operating).
Definition at line 175 of file model.h.
References deathtime_.
void cyclus::Model::Decommission () [virtual]
Decommissions the model, removing it from the simulation.
Results in destruction of the model object.
Reimplemented in cyclus::FacilityModel.
Definition at line 132 of file model.cc.
References CLOG, ctx_, cyclus::Context::DelModel(), cyclus::LEV_INFO3, and name().
void cyclus::Model::Deploy (Model * parent = NULL) [virtual]
creates the parent-child link and invokes the core-level and module-level enter simulation methods
Parameters:
parent this model's parent
Reimplemented in cyclus::InstModel, cyclus::FacilityModel, and cyclus::RegionModel.
Definition at line 108 of file model.cc.
References AddToTable(), birthtime_, children_, CLOG, ctx_, id(), cyclus::LEV_DEBUG1, cyclus::LEV_DEBUG2, cyclus::LEV_DEBUG3, ModelImpl(), name(), parent(), parent_, parent_id_, and cyclus::Context::time().
Referenced by cyclus::RegionModel::AddChildrenToTree(), cyclus::InstModel::Build(), cyclus::XMLFlatLoader::LoadInitialAgents(), and cyclus::XMLFileLoader::LoadInitialAgents().
std::vector< std::string > cyclus::Model::GetTreePrintOuts (Model * m)
returns a vector of strings representing the parent-child tree at the node for Model m
Parameters:
m the model node to base as the root of this print tree
Definition at line 151 of file model.cc.
References children(), and name().
Referenced by PrintChildren().
const int cyclus::Model::id () const [inline]
get model instance ID
Definition at line 147 of file model.h.
References id_.
Referenced by cyclus::ResTracker::Create(), Deploy(), cyclus::FacilityModel::InitFrom(), cyclus::XMLFlatLoader::LoadInitialAgents(), cyclus::XMLFileLoader::LoadInitialAgents(), cyclus::TradeExecutor< T >::RecordTrades(), cyclus::Timer::RegisterTickListener(), and ~Model().
std::string cyclus::Model::InformErrorMsg (std::string msg) [protected, virtual]
adds model-specific information prefix to an error message
Definition at line 31 of file model.cc.
References context(), model_impl_, name_, and cyclus::Context::time().
void cyclus::Model::InitFrom (QueryEngine * qe) [virtual]
Initializes a model by reading parameters from the passed QueryEngine.
This method must be implemented by all models. This method must call the superclass' InitFrom(QueryEngine*) method. The InitFrom method should only initialize this class' members - not inherited state. The superclass InitFrom should generally be called before any other work is done.
Model parameters in the QueryEngine are scoped in the "model/[model-class-name]" path. The model's class-name can be retrieved from the ModelImpl method. The superclass InitFrom expects the QueryEngine passed to it to be scoped identically - do NOT pass a changed-scope QueryEngine to the superclass.
Example:
 class MyModelClass : virtual public cyclus::FacilityModel {
   // ...
   void InitFrom(QueryEngine* qe) {
     cyclus::FacilityModel::InitFrom(qe); //
     // now do MyModelClass' initialitions, e.g.:
     qe = qe->QueryElement("model/" + ModelImpl()); // rescope the QueryEngine
     // retrieve all model params
     in_commod_ = qe->GetElementContent("incommod");
     // ...
   };
   // ...
 };
Reimplemented in cyclus::RegionModel, cyclus::FacilityModel, and cyclus::InstModel.
Definition at line 41 of file model.cc.
References CLOG, cyclus::QueryEngine::GetElementContent(), cyclus::LEV_DEBUG1, and name_.
Referenced by cyclus::XMLFlatLoader::LoadInitialAgents(), and cyclus::XMLFileLoader::LoadInitialAgents().
void cyclus::Model::InitFrom (Model * m) [protected]
Initializes a model by copying parameters from the passed model m.
This method must be implemented by all models. This method must call the superclass' InitFrom method. The InitFrom method should only initialize this class' members - not inherited state. The superclass InitFrom should generally be called before any other work is done.
Parameters:
m the model containing state that should be used to initialize this model.
Example:
 class MyModelClass : virtual public cyclus::FacilityModel {
   // ...
   void InitFrom(MyModelClass* m) {
     cyclus::FacilityModel::InitFrom(m); // call superclass' InitFrom
     // now do MyModelClass' initialitions, e.g.:
     my_var_ = m->my_var_;
     // ...
   };
   // ...
 };
Definition at line 21 of file model.cc.
References ctx_, id_, model_impl_, cyclus::Context::model_list_, model_type_, name_, and next_id_.
const std::string cyclus::Model::model_type () const [inline]
returns a string that describes the model subclass (e.g. Region, etc.)
Definition at line 155 of file model.h.
References model_type_.
Referenced by AddToTable(), cyclus::BuildMasterSchema(), cyclus::XMLFlatLoader::LoadInitialAgents(), cyclus::XMLFileLoader::LoadInitialAgents(), and str().
const std::string cyclus::Model::ModelImpl ()
get model implementation name
Definition at line 168 of file model.cc.
References model_impl_.
Referenced by AddToTable(), Deploy(), cyclus::XMLFlatLoader::LoadInitialAgents(), and cyclus::XMLFileLoader::LoadInitialAgents().
const std::string cyclus::Model::name () const [inline]
get model instance name
Definition at line 144 of file model.h.
References name_.
Referenced by cyclus::InstModel::AddPrototypeToInitialBuild(), AddToTable(), cyclus::FacilityModel::Decommission(), Decommission(), Deploy(), cyclus::FacilityModel::FacName(), GetTreePrintOuts(), cyclus::InstModel::InitFrom(), cyclus::RegionModel::InitInstitutionNames(), cyclus::XMLFlatLoader::LoadInitialAgents(), cyclus::XMLFileLoader::LoadInitialAgents(), PrintChildren(), cyclus::Timer::RegisterTickListener(), cyclus::FacilityModel::SetInstName(), cyclus::InstModel::str(), cyclus::InstModel::ThrowErrorIfPrototypeIsntAvailable(), cyclus::InstModel::Tock(), and ~Model().
Model* cyclus::Model::parent () const [inline]
returns parent of this model
Definition at line 164 of file model.h.
References parent_.
Referenced by cyclus::ResourceExchange< T >::AdjustPrefs_(), Deploy(), cyclus::FacilityModel::FacInst(), cyclus::InstModel::GetRegion(), and cyclus::InstModel::str().
const int cyclus::Model::parent_id () const [inline]
returns the parent's id
Definition at line 167 of file model.h.
References parent_id_.
std::string cyclus::Model::PrintChildren ()
recursively prints the parent-child tree
Definition at line 138 of file model.cc.
References children_, GetTreePrintOuts(), and name().
virtual std::string cyclus::Model::schema () [inline, virtual]
Returns a module's xml rng schema for initializing from input files.
All concrete models should override this method.
Definition at line 139 of file model.h.
Referenced by cyclus::BuildFlatMasterSchema(), and cyclus::BuildMasterSchema().
void cyclus::Model::SetModelImpl (std::string new_impl) [inline]
set model implementation
Definition at line 150 of file model.h.
References model_impl_.
Referenced by cyclus::XMLFlatLoader::LoadInitialAgents(), and cyclus::XMLFileLoader::LoadInitialAgents().
std::string cyclus::Model::str () [virtual]
every model should be able to print a verbose description
Reimplemented in cyclus::FacilityModel, cyclus::RegionModel, and cyclus::InstModel.
Definition at line 95 of file model.cc.
References id_, model_impl_, model_type(), name_, and parent_id_.
Member Data Documentation
int cyclus::Model::birthtime_ [private]
born on date of this model
Definition at line 234 of file model.h.
Referenced by birthtime(), Deploy(), and ~Model().
std::vector<Model*> cyclus::Model::children_ [private]
children of this model
Definition at line 223 of file model.h.
Referenced by children(), Deploy(), PrintChildren(), and ~Model().
Context* cyclus::Model::ctx_ [private]
Definition at line 248 of file model.h.
Referenced by AddToTable(), context(), Decommission(), Deploy(), InitFrom(), Model(), and ~Model().
int cyclus::Model::deathtime_ [private]
died on date of this model
Definition at line 237 of file model.h.
Referenced by deathtime(), and ~Model().
int cyclus::Model::id_ [private]
an instance-unique ID for the model
Definition at line 246 of file model.h.
Referenced by id(), InitFrom(), Model(), str(), and ~Model().
std::string cyclus::Model::model_impl_ [private]
concrete type of a model (e.g. "MyReactorModel")
Definition at line 243 of file model.h.
Referenced by InformErrorMsg(), InitFrom(), ModelImpl(), SetModelImpl(), and str().
std::string cyclus::Model::model_type_ [protected]
describes the model subclass (e.g.
Region, Inst, etc.). The in-core subclasses must set this variable in their constructor(s).
Definition at line 213 of file model.h.
Referenced by cyclus::FacilityModel::FacilityModel(), InitFrom(), cyclus::InstModel::InstModel(), model_type(), and cyclus::RegionModel::RegionModel().
std::string cyclus::Model::name_ [private]
every instance of a model should have a name
Definition at line 240 of file model.h.
Referenced by InformErrorMsg(), InitFrom(), name(), and str().
int cyclus::Model::next_id_ = 0 [static, private]
Stores the next available facility ID.
Definition at line 220 of file model.h.
Referenced by InitFrom().
Model* cyclus::Model::parent_ [private]
parent of this model
Definition at line 226 of file model.h.
Referenced by Deploy(), parent(), and ~Model().
int cyclus::Model::parent_id_ [private]
parent's ID of this model Note: we keep the parent id in the model so we can reference it even if the parent is deallocated.
Definition at line 231 of file model.h.
Referenced by AddToTable(), Deploy(), parent_id(), and str().
The documentation for this class was generated from the following files:
model.h
model.cc