CYCLUS: cyclus::InstModel Class Reference
cyclus::InstModel Class Reference
The InstModel class is the abstract class/interface used by all institution models.
#include <inst_model.h>
Public Member Functions
PrototypeIterator BeginPrototype ()
return the first prototype
void Build (std::string proto_name)
builds a prototype
virtual void Deploy (Model *parent)
perform all tasks required when an inst enters the simulation
PrototypeIterator EndPrototype ()
return the last prototype
int GetNumFacilities ()
reports number of facilities in this inst
RegionModel * GetRegion ()
returns this institution's region
virtual void InitFrom (QueryEngine *qe)
Initalize the InstModel from a QueryEngine.
InstModel (Context *ctx)
Default constructor for InstModel Class.
bool IsAvailablePrototype (std::string proto_name)
Checks if prototype is in the prototype list.
int NPrototypes ()
return the number of prototypes this inst can build
virtual std::string str ()
every model should be able to print a verbose description
virtual void Tick (int time)
Each institution is prompted to do its beginning-of-time-step stuff at the tick of the timer.
virtual void Tock (int time)
Each institution is prompted to its end-of-time-step stuff on the tock of the timer.
virtual ~InstModel ()
every model should be destructable
Protected Member Functions
void AddAvailablePrototype (std::string proto_name)
add a prototoype to the set of available prototypes
void AddPrototypeToInitialBuild (QueryEngine *qe)
Adds a prototype build order to initial_build_order_.
void InitFrom (InstModel *m)
virtual void RegisterAvailablePrototype (std::string proto_name)
perform any actions required after prototype has been added to the list of available prototypes
virtual void RegisterCloneAsBuilt (Model *clone)
perform any registration functionality after a clone has been built
virtual void RegisterCloneAsDecommissioned (Model *clone)
perform any registration functionality before a clone is decommissioned(deleted)
void ThrowErrorIfPrototypeIsntAvailable (std::string p)
checks if a prototype is in its list of available prototypes if not, it throws an error
Private Attributes
std::map< std::string, int > initial_build_order_
the initial prototypes to build
PrototypeSet prototypes_
The Inst's set of available prototypes to build.
Detailed Description
The InstModel class is the abstract class/interface used by all institution models.
Introduction The InstModel type assists in defining the
region-institution-facility hierarchy in Cyclus. A InstModel institution is an actor associated with a set of facilities for which it is responsible. An InstModel may be used to adjust preferences in the ResourceExchange to make material routing decisions based on interfacility relationships. Deployment is a primary differentiator between different InstModel implementations.
Like all model implementations, there are a number of implementations that are distributed as part of the core Cyclus application as well as implementations contributed by third-party developers. The links below descrie parameters necessary for the complete definition of an implemented instituion.
Available Core Implementations
FixedInst: This institution is unchanging and is statically associated with facilities that are deployed by some other entity (such as the region or the logician.
Anticipated Core Implementations
DeploymentInst: This institution deploys allowed facilities according to a demand curve.
Third Party Implementations
(None)
Definition at line 50 of file inst_model.h.
Constructor & Destructor Documentation
cyclus::InstModel::InstModel (Context * ctx)
Default constructor for InstModel Class.
Definition at line 19 of file inst_model.cc.
References cyclus::Model::model_type_.
virtual cyclus::InstModel::~InstModel () [inline, virtual]
every model should be destructable
Definition at line 64 of file inst_model.h.
Member Function Documentation
void cyclus::InstModel::AddAvailablePrototype (std::string proto_name) [protected]
add a prototoype to the set of available prototypes
Parameters:
proto_name the name of the prototype to add
Definition at line 62 of file inst_model.cc.
References prototypes_, and RegisterAvailablePrototype().
Referenced by InitFrom().
void cyclus::InstModel::AddPrototypeToInitialBuild (QueryEngine * qe) [protected]
Adds a prototype build order to initial_build_order_.
Parameters:
qe a pointer to a QueryEngine object containing intialization data
Definition at line 71 of file inst_model.cc.
References CLOG, cyclus::QueryEngine::GetElementContent(), initial_build_order_, cyclus::LEV_DEBUG3, cyclus::Model::name(), and ThrowErrorIfPrototypeIsntAvailable().
Referenced by InitFrom().
PrototypeIterator cyclus::InstModel::BeginPrototype () [inline]
return the first prototype
Definition at line 117 of file inst_model.h.
References prototypes_.
void cyclus::InstModel::Build (std::string proto_name)
builds a prototype
Parameters:
proto_name the name of the prototype to build
Definition at line 174 of file inst_model.cc.
References cyclus::Model::context(), cyclus::Context::CreateModel(), cyclus::Model::Deploy(), RegisterCloneAsBuilt(), and ThrowErrorIfPrototypeIsntAvailable().
Referenced by Deploy().
void cyclus::InstModel::Deploy (Model * parent) [virtual]
perform all tasks required when an inst enters the simulation
Reimplemented from cyclus::Model.
Definition at line 106 of file inst_model.cc.
References Build(), and initial_build_order_.
PrototypeIterator cyclus::InstModel::EndPrototype () [inline]
return the last prototype
Definition at line 124 of file inst_model.h.
References prototypes_.
int cyclus::InstModel::GetNumFacilities () [inline]
reports number of facilities in this inst
Definition at line 145 of file inst_model.h.
References cyclus::Model::children().
RegionModel* cyclus::InstModel::GetRegion () [inline]
returns this institution's region
Definition at line 138 of file inst_model.h.
References cyclus::Model::parent().
void cyclus::InstModel::InitFrom (QueryEngine * qe) [virtual]
Initalize the InstModel from a QueryEngine.
Calls the init function.
Parameters:
qe a pointer to a QueryEngine object containing intialization data
Reimplemented from cyclus::Model.
Definition at line 31 of file inst_model.cc.
References AddAvailablePrototype(), AddPrototypeToInitialBuild(), cyclus::QueryEngine::GetElementContent(), cyclus::Model::name(), cyclus::QueryEngine::NElementsMatchingQuery(), and cyclus::QueryEngine::QueryElement().
Referenced by InitFrom().
void cyclus::InstModel::InitFrom (InstModel * m) [protected]
Definition at line 24 of file inst_model.cc.
References InitFrom(), initial_build_order_, and prototypes_.
bool cyclus::InstModel::IsAvailablePrototype (std::string proto_name) [inline]
Checks if prototype is in the prototype list.
Definition at line 131 of file inst_model.h.
References prototypes_.
Referenced by ThrowErrorIfPrototypeIsntAvailable().
int cyclus::InstModel::NPrototypes () [inline]
return the number of prototypes this inst can build
Definition at line 110 of file inst_model.h.
References prototypes_.
void cyclus::InstModel::RegisterAvailablePrototype (std::string proto_name) [protected, virtual]
perform any actions required after prototype has been added to the list of available prototypes
Parameters:
proto_name the name of prototype to register
Definition at line 68 of file inst_model.cc.
Referenced by AddAvailablePrototype().
void cyclus::InstModel::RegisterCloneAsBuilt (Model * clone) [protected, virtual]
perform any registration functionality after a clone has been built
Parameters:
clone the built (cloned) prototype
Definition at line 182 of file inst_model.cc.
Referenced by Build().
void cyclus::InstModel::RegisterCloneAsDecommissioned (Model * clone) [protected, virtual]
perform any registration functionality before a clone is decommissioned(deleted)
Parameters:
clone the to-be-decommissioned
Definition at line 185 of file inst_model.cc.
Referenced by Tock().
std::string cyclus::InstModel::str () [virtual]
every model should be able to print a verbose description
Reimplemented from cyclus::Model.
Definition at line 97 of file inst_model.cc.
References cyclus::Model::name(), and cyclus::Model::parent().
void cyclus::InstModel::ThrowErrorIfPrototypeIsntAvailable (std::string p) [protected]
checks if a prototype is in its list of available prototypes if not, it throws an error
Parameters:
p the prototype to check for
Definition at line 86 of file inst_model.cc.
References IsAvailablePrototype(), and cyclus::Model::name().
Referenced by AddPrototypeToInitialBuild(), and Build().
void cyclus::InstModel::Tick (int time) [virtual]
Each institution is prompted to do its beginning-of-time-step stuff at the tick of the timer.
Default behavior is to ignore the tick.
Parameters:
time is the time to perform the tick
Implements cyclus::TimeListener.
Definition at line 129 of file inst_model.cc.
References cyclus::Model::children().
void cyclus::InstModel::Tock (int time) [virtual]
Each institution is prompted to its end-of-time-step stuff on the tock of the timer.
Default behavior is to ignore the tock.
Parameters:
time is the time to perform the tock
Implements cyclus::TimeListener.
Definition at line 145 of file inst_model.cc.
References cyclus::FacilityModel::CheckDecommissionCondition(), cyclus::Model::children(), CLOG, cyclus::FacilityModel::Decommission(), cyclus::LEV_INFO3, cyclus::FacilityModel::LifetimeReached(), cyclus::Model::name(), RegisterCloneAsDecommissioned(), and cyclus::FacilityModel::Tock().
Member Data Documentation
std::map<std::string, int> cyclus::InstModel::initial_build_order_ [private]
the initial prototypes to build
Definition at line 207 of file inst_model.h.
Referenced by AddPrototypeToInitialBuild(), Deploy(), and InitFrom().
PrototypeSet cyclus::InstModel::prototypes_ [private]
The Inst's set of available prototypes to build.
Definition at line 202 of file inst_model.h.
Referenced by AddAvailablePrototype(), BeginPrototype(), EndPrototype(), InitFrom(), IsAvailablePrototype(), and NPrototypes().
The documentation for this class was generated from the following files:
inst_model.h
inst_model.cc