CYCLUS: cyclus::XMLFlatLoader Class Reference
cyclus::XMLFlatLoader Class Reference
a class that encapsulates the methods needed to load input to a cyclus simulation from xml
#include <xml_flat_loader.h>
Public Member Functions
XMLFlatLoader (Context *ctx, std::string schema_path, const std::string load_filename="")
Protected Member Functions
void LoadInitialAgents ()
Creates all initial agent instances from the input file.
virtual std::string master_schema ()
Detailed Description
a class that encapsulates the methods needed to load input to a cyclus simulation from xml
Definition at line 17 of file xml_flat_loader.h.
Constructor & Destructor Documentation
cyclus::XMLFlatLoader::XMLFlatLoader (Context * ctx, std::string schema_path, const std::string load_filename = "") [inline]
Definition at line 19 of file xml_flat_loader.h.
Member Function Documentation
void cyclus::XMLFlatLoader::LoadInitialAgents () [protected, virtual]
Creates all initial agent instances from the input file.
Reimplemented from cyclus::XMLFileLoader.
Definition at line 54 of file xml_flat_loader.cc.
References cyclus::Context::AddPrototype(), CLOG, cyclus::Context::CreateModel(), cyclus::XMLFileLoader::ctx_, cyclus::Model::Deploy(), cyclus::QueryEngine::GetElementContent(), cyclus::QueryEngine::GetElementName(), cyclus::Model::id(), cyclus::Model::InitFrom(), cyclus::LEV_DEBUG3, cyclus::Model::model_type(), cyclus::Model::ModelImpl(), cyclus::XMLFileLoader::modules_, cyclus::Model::name(), cyclus::XMLQueryEngine::NElementsMatchingQuery(), cyclus::XMLFileLoader::parser_, cyclus::QueryEngine::QueryElement(), and cyclus::Model::SetModelImpl().
std::string cyclus::XMLFlatLoader::master_schema () [protected, virtual]
Reimplemented from cyclus::XMLFileLoader.
Definition at line 49 of file xml_flat_loader.cc.
References cyclus::BuildFlatMasterSchema(), and cyclus::XMLFileLoader::schema_path_.
The documentation for this class was generated from the following files:
xml_flat_loader.h
xml_flat_loader.cc