CYCLUS: cyclus::MassTable Class Reference
cyclus::MassTable Class Reference
The MassTable class provides an interface to the mass.sqlite database, providing a robust and correct mass lookup by isotope.
#include <mass_table.h>
Classes
struct Nuclide
Defines the structure of data associated with each row entry in the mass database.
Public Member Functions
int GetAtomicNum (int tope)
get the Atomic Number of an isotope according to its identifier.
double GramsPerMol (int tope)
get the Mass, a double, of an isotope according to its identifier.
MassTable ()
Default constructor for the MassTable class.
~MassTable ()
Destructor for the NullFacility class.
Static Public Member Functions
static MassTable * Instance ()
Gives all simulation objects global access to the Env by returning a pointer to it.
Protected Types
typedef struct
cyclus::MassTable::Nuclide Nuclide
Defines the structure of data associated with each row entry in the mass database.
Protected Member Functions
void InitializeSQL ()
a function to initialize a large array of Nuclide structs via the SQLite/C++ API
Protected Attributes
std::map< int, int > isoIndex_
a map for index lookup in the nuclide vector.
int nuclide_len_
The integer length (number of rows) of the mass.h5/ame03/nuclide/.
std::vector< Nuclide > nuclide_vec_
The vector of nuclide structs that holds the data in the mass table.
Static Private Attributes
static MassTable * instance_ = 0
A pointer to this MassTable once it has been initialized.
Detailed Description
The MassTable class provides an interface to the mass.sqlite database, providing a robust and correct mass lookup by isotope.
Definition at line 18 of file mass_table.h.
Member Typedef Documentation
typedef struct cyclus::MassTable::Nuclide cyclus::MassTable::Nuclide [protected]
Defines the structure of data associated with each row entry in the mass database.
Right now, strings are a little funky, so the names
Constructor & Destructor Documentation
cyclus::MassTable::MassTable ()
Default constructor for the MassTable class.
Initializes the data from the provided mass.h5 file.
Definition at line 27 of file mass_table.cc.
References InitializeSQL().
Referenced by Instance().
cyclus::MassTable::~MassTable ()
Destructor for the NullFacility class.
Makes certain to delete all appropriate data on the stack.
Definition at line 32 of file mass_table.cc.
Member Function Documentation
int cyclus::MassTable::GetAtomicNum (int tope)
get the Atomic Number of an isotope according to its identifier.
Parameters:
tope is the isotope identifier of type Iso, which is an int typedef
Returns:
int the atomic number of the tope isotope.
double cyclus::MassTable::GramsPerMol (int tope)
get the Mass, a double, of an isotope according to its identifier.
Parameters:
tope is the isotope identifier of type Iso, which is an int typedef
Returns:
the mass, a double, of the tope isotope.
Definition at line 37 of file mass_table.cc.
References isoIndex_, and nuclide_vec_.
void cyclus::MassTable::InitializeSQL () [protected]
a function to initialize a large array of Nuclide structs via the SQLite/C++ API
Definition at line 43 of file mass_table.cc.
References cyclus::Env::GetBuildPath(), isoIndex_, nuclide_len_, nuclide_vec_, and cyclus::SqliteDb::Query().
Referenced by MassTable().
MassTable * cyclus::MassTable::Instance () [static]
Gives all simulation objects global access to the Env by returning a pointer to it.
Returns:
a pointer to the MassTable
Definition at line 17 of file mass_table.cc.
References instance_, and MassTable().
Member Data Documentation
MassTable * cyclus::MassTable::instance_ = 0 [static, private]
A pointer to this MassTable once it has been initialized.
Definition at line 23 of file mass_table.h.
Referenced by Instance().
std::map<int, int> cyclus::MassTable::isoIndex_ [protected]
a map for index lookup in the nuclide vector.
Definition at line 90 of file mass_table.h.
Referenced by GramsPerMol(), and InitializeSQL().
int cyclus::MassTable::nuclide_len_ [protected]
The integer length (number of rows) of the mass.h5/ame03/nuclide/.
Definition at line 80 of file mass_table.h.
Referenced by InitializeSQL().
std::vector<Nuclide> cyclus::MassTable::nuclide_vec_ [protected]
The vector of nuclide structs that holds the data in the mass table.
Definition at line 85 of file mass_table.h.
Referenced by GramsPerMol(), and InitializeSQL().
The documentation for this class was generated from the following files:
mass_table.h
mass_table.cc