CYCLUS: cyclus::DynamicModule Class Reference
cyclus::DynamicModule Class Reference
#include <dynamic_module.h>
Public Member Functions
void CloseLibrary ()
closes the loaded module dynamic lib
Model * ConstructInstance (Context *ctx)
construct an instance of this module
DynamicModule (std::string name)
Creates a new dynamically loadable module.
std::string name ()
std::string path ()
If this path for this module has not been discovered yet, path searches for it.
Static Public Member Functions
static const std::string Suffix ()
Private Member Functions
void OpenLibrary ()
uses dlopen to open the module shared lib
void SetConstructor ()
sets the constructor member
Private Attributes
std::string abs_path_
the path to the library
ModelCtor * constructor_
a functor for the constructor
std::string constructor_name_
the name of all module constructor functions
void * module_library_
the library to open and close
std::string module_name_
the name of the module
Detailed Description
Definition at line 14 of file dynamic_module.h.
Constructor & Destructor Documentation
cyclus::DynamicModule::DynamicModule (std::string name)
Creates a new dynamically loadable module.
Parameters:
name the name of the module
Definition at line 23 of file dynamic_module.cc.
References abs_path_, cyclus::Env::FindModuleLib(), module_name_, OpenLibrary(), SetConstructor(), and Suffix().
Member Function Documentation
void cyclus::DynamicModule::CloseLibrary ()
closes the loaded module dynamic lib
Definition at line 42 of file unix_helper_functions.h.
References module_library_.
Referenced by cyclus::BuildFlatMasterSchema(), and cyclus::BuildMasterSchema().
Model * cyclus::DynamicModule::ConstructInstance (Context * ctx)
construct an instance of this module
Returns:
a fresh instance
Definition at line 40 of file dynamic_module.cc.
References constructor_.
Referenced by cyclus::BuildFlatMasterSchema(), and cyclus::BuildMasterSchema().
std::string cyclus::DynamicModule::name ()
Returns:
the module name
Definition at line 45 of file dynamic_module.cc.
References module_name_.
void cyclus::DynamicModule::OpenLibrary () [private]
uses dlopen to open the module shared lib
Definition at line 14 of file unix_helper_functions.h.
References abs_path_, and module_library_.
Referenced by DynamicModule().
std::string cyclus::DynamicModule::path ()
If this path for this module has not been discovered yet, path searches for it.
Exceptions:
IOError the library path was not found
Returns:
the filepath of the dynamic library.
Definition at line 50 of file dynamic_module.cc.
References abs_path_.
void cyclus::DynamicModule::SetConstructor () [private]
sets the constructor member
Definition at line 27 of file unix_helper_functions.h.
References constructor_, constructor_name_, and module_library_.
Referenced by DynamicModule().
const std::string cyclus::DynamicModule::Suffix () [static]
Returns:
the global library suffix
Definition at line 18 of file dynamic_module.cc.
References SUFFIX.
Referenced by DynamicModule().
Member Data Documentation
std::string cyclus::DynamicModule::abs_path_ [private]
the path to the library
Definition at line 42 of file dynamic_module.h.
Referenced by DynamicModule(), OpenLibrary(), and path().
ModelCtor* cyclus::DynamicModule::constructor_ [private]
a functor for the constructor
Definition at line 54 of file dynamic_module.h.
Referenced by ConstructInstance(), and SetConstructor().
std::string cyclus::DynamicModule::constructor_name_ [private]
the name of all module constructor functions
Definition at line 48 of file dynamic_module.h.
Referenced by SetConstructor().
void* cyclus::DynamicModule::module_library_ [private]
the library to open and close
Definition at line 51 of file dynamic_module.h.
Referenced by CloseLibrary(), OpenLibrary(), and SetConstructor().
std::string cyclus::DynamicModule::module_name_ [private]
the name of the module
Definition at line 45 of file dynamic_module.h.
Referenced by DynamicModule(), and name().
The documentation for this class was generated from the following files:
dynamic_module.h
dynamic_module.cc
unix_helper_functions.h
windows_helper_functions.h