CYCLUS: cyclus::Context Class Reference
cyclus::Context Class Reference
A simulation context that provides access to necessary simulation-global functions and state.
#include <context.h>
Public Member Functions
void AddPrototype (std::string name, Model *m)
Adds a prototype to a simulation-wide accessible list.
void AddRecipe (std::string name, Composition::Ptr c)
Adds a composition recipe to a simulation-wide accessible list.
Context (Timer *ti, Recorder *rec)
Creates a new context working with the specified timer and datum manager.
template<class T >
T * CreateModel (std::string proto_name)
Create a new model by cloning the named prototype.
void DelModel (Model *m)
Destructs and cleans up m (and it's children recursively).
Composition::Ptr GetRecipe (std::string name)
Retrieve a registered recipe.
void InitTime (int start, int duration, int decay, int m0=1, int y0=2010, std::string handle="")
Initializes the simulation time parameters.
Datum * NewDatum (std::string title)
See Recorder::NewDatum documentation.
int NextTransactionID ()
void RegisterTimeListener (TimeListener *tl)
See Timer::RegisterTickListener documentation.
void RegisterTrader (Trader *e)
Registers an agent as a participant in resource exchanges.
int sim_dur ()
Returns the number of timesteps in the entire simulation.
boost::uuids::uuid sim_id ()
See Recorder::sim_id documentation.
ExchangeSolver * solver ()
Returns the exchange solver associated with this context.
void solver (ExchangeSolver *solver)
sets the solver associated with this context
int start_time ()
Returns the simulation starting timestep.
int time ()
Returns the current simulation timestep.
const std::set< Trader * > & traders () const
void UnregisterTrader (Trader *e)
Unregisters an agent as a participant in resource exchanges.
~Context ()
Clean up resources including destructing the solver and all models the context is aware of.
Private Attributes
std::set< Model * > model_list_
std::map< std::string, Model * > protos_
Recorder * rec_
std::map< std::string,
Composition::Ptr > recipes_
ExchangeSolver * solver_
Timer * ti_
std::set< Trader * > traders_
int trans_id_
Friends
class Model
Detailed Description
A simulation context that provides access to necessary simulation-global functions and state.
All code that writes to the output database, needs to know simulation time, creates/deploys facilities, and/or uses loaded composition recipes will need a context pointer. In general, all global state should be accessed through a simulation context.
Warning:
the context takes ownership of and manages the lifetime/destruction of all models constructed with it (including Cloned models). Models should generally NEVER be allocated on the stack.
the context takes ownership of the solver and will manage its destruction.
Definition at line 33 of file context.h.
Constructor & Destructor Documentation
cyclus::Context::Context (Timer * ti, Recorder * rec)
Creates a new context working with the specified timer and datum manager.
The timer does not have to be initialized (yet).
Definition at line 13 of file context.cc.
cyclus::Context::~Context ()
Clean up resources including destructing the solver and all models the context is aware of.
Definition at line 16 of file context.cc.
References DelModel(), model_list_, and solver_.
Member Function Documentation
void cyclus::Context::AddPrototype (std::string name, Model * m)
Adds a prototype to a simulation-wide accessible list.
Definition at line 43 of file context.cc.
References protos_.
Referenced by cyclus::XMLFlatLoader::LoadInitialAgents(), and cyclus::XMLFileLoader::LoadInitialAgents().
void cyclus::Context::AddRecipe (std::string name, Composition::Ptr c)
Adds a composition recipe to a simulation-wide accessible list.
Agents should NOT add their own recipes.
Definition at line 47 of file context.cc.
References recipes_.
Referenced by cyclus::XMLFileLoader::LoadRecipes().
template<class T > T* cyclus::Context::CreateModel (std::string proto_name) [inline]
Create a new model by cloning the named prototype.
The returned model is not initialized as a simulation participant.
Definition at line 72 of file context.h.
References cyclus::Model::Clone(), DelModel(), and protos_.
Referenced by cyclus::RegionModel::AddChildrenToTree(), cyclus::InstModel::Build(), and cyclus::XMLFlatLoader::LoadInitialAgents().
void cyclus::Context::DelModel (Model * m)
Destructs and cleans up m (and it's children recursively).
Definition at line 31 of file context.cc.
References model_list_.
Referenced by cyclus::BuildFlatMasterSchema(), cyclus::BuildMasterSchema(), CreateModel(), cyclus::Model::Decommission(), ~Context(), and cyclus::Model::~Model().
Composition::Ptr cyclus::Context::GetRecipe (std::string name)
Retrieve a registered recipe.
This is intended for retrieving compositions loaded from an input file(s) at the start of a simulation and NOT for communicating compositions between facilities during the simulation.
Definition at line 51 of file context.cc.
References recipes_.
void cyclus::Context::InitTime (int start, int duration, int decay, int m0 = 1, int y0 = 2010, std::string handle = "")
Initializes the simulation time parameters.
Should only be called once - NOT idempotent.
Definition at line 58 of file context.cc.
References cyclus::Timer::Initialize(), and ti_.
Referenced by cyclus::XMLFileLoader::LoadControlParams().
Datum * cyclus::Context::NewDatum (std::string title)
See Recorder::NewDatum documentation.
Definition at line 79 of file context.cc.
References cyclus::Recorder::NewDatum(), and rec_.
Referenced by cyclus::Model::AddToTable(), cyclus::ResTracker::Create(), cyclus::Timer::LogTimeData(), cyclus::ResTracker::Record(), cyclus::Composition::Record(), cyclus::TradeExecutor< T >::RecordTrades(), cyclus::XMLFileLoader::XMLFileLoader(), and cyclus::Model::~Model().
int cyclus::Context::NextTransactionID () [inline]
Returns:
the next transaction id
Definition at line 119 of file context.h.
References trans_id_.
Referenced by cyclus::TradeExecutor< T >::RecordTrades().
void cyclus::Context::RegisterTimeListener (TimeListener * tl)
See Timer::RegisterTickListener documentation.
Definition at line 75 of file context.cc.
References cyclus::Timer::RegisterTickListener(), and ti_.
Referenced by cyclus::RegionModel::AddRegionAsRootNode().
void cyclus::Context::RegisterTrader (Trader * e) [inline]
Registers an agent as a participant in resource exchanges.
Definition at line 52 of file context.h.
References traders_.
Referenced by cyclus::FacilityModel::Deploy().
int cyclus::Context::sim_dur ()
Returns the number of timesteps in the entire simulation.
Definition at line 71 of file context.cc.
References cyclus::Timer::dur(), and ti_.
Referenced by cyclus::FacilityModel::InitFrom().
boost::uuids::uuid cyclus::Context::sim_id ()
See Recorder::sim_id documentation.
Definition at line 39 of file context.cc.
References rec_, and cyclus::Recorder::sim_id().
ExchangeSolver* cyclus::Context::solver () [inline]
Returns the exchange solver associated with this context.
Definition at line 122 of file context.h.
References solver_.
Referenced by cyclus::ExchangeManager< T >::Execute(), and cyclus::XMLFileLoader::LoadSolver().
void cyclus::Context::solver (ExchangeSolver * solver) [inline]
sets the solver associated with this context
Definition at line 125 of file context.h.
References solver(), and solver_.
Referenced by solver().
int cyclus::Context::start_time ()
Returns the simulation starting timestep.
Definition at line 67 of file context.cc.
References cyclus::Timer::start_time(), and ti_.
int cyclus::Context::time ()
Returns the current simulation timestep.
Definition at line 63 of file context.cc.
References ti_, and cyclus::Timer::time().
Referenced by cyclus::Model::Deploy(), cyclus::Model::InformErrorMsg(), cyclus::Material::Material(), cyclus::ResTracker::Record(), cyclus::TradeExecutor< T >::RecordTrades(), and cyclus::Model::~Model().
const std::set<Trader*>& cyclus::Context::traders () const [inline]
Returns:
the current set of facilities in the simulation
Definition at line 65 of file context.h.
References traders_.
Referenced by cyclus::ResourceExchange< T >::AddAllBids(), and cyclus::ResourceExchange< T >::AddAllRequests().
void cyclus::Context::UnregisterTrader (Trader * e) [inline]
Unregisters an agent as a participant in resource exchanges.
Definition at line 57 of file context.h.
References traders_.
Referenced by cyclus::FacilityModel::Decommission().
Friends And Related Function Documentation
friend class Model [friend]
Definition at line 35 of file context.h.
Member Data Documentation
std::set<Model*> cyclus::Context::model_list_ [private]
Definition at line 131 of file context.h.
Referenced by DelModel(), cyclus::Model::InitFrom(), cyclus::Model::Model(), ~Context(), and cyclus::Model::~Model().
std::map<std::string, Model*> cyclus::Context::protos_ [private]
Definition at line 128 of file context.h.
Referenced by AddPrototype(), and CreateModel().
Recorder* cyclus::Context::rec_ [private]
Definition at line 135 of file context.h.
Referenced by NewDatum(), and sim_id().
std::map<std::string, Composition::Ptr> cyclus::Context::recipes_ [private]
Definition at line 130 of file context.h.
Referenced by AddRecipe(), and GetRecipe().
ExchangeSolver* cyclus::Context::solver_ [private]
Definition at line 134 of file context.h.
Referenced by solver(), and ~Context().
Timer* cyclus::Context::ti_ [private]
Definition at line 133 of file context.h.
Referenced by InitTime(), RegisterTimeListener(), sim_dur(), start_time(), and time().
std::set<Trader*> cyclus::Context::traders_ [private]
Definition at line 129 of file context.h.
Referenced by RegisterTrader(), traders(), and UnregisterTrader().
int cyclus::Context::trans_id_ [private]
Definition at line 136 of file context.h.
Referenced by NextTransactionID().
The documentation for this class was generated from the following files:
context.h
context.cc