CYCLUS: cyclus::QueryEngine Class Reference
cyclus::QueryEngine Class Reference
This is a base class that defines the API used by any engine representing an input format.
#include <query_engine.h>
Public Member Functions
virtual std::string GetElementContent (std::string query, int index=0)=0
investigates the current status and returns a string representing the content of a query at a given index
virtual std::string GetElementName (int index=0)=0
investigates the current status and returns a string representing the name of a given index
virtual int NElements ()=0
virtual int NElementsMatchingQuery (std::string query)=0
investigates the current status and returns the number of elements matching a query
QueryEngine * QueryElement (std::string query, int index=0)
populates a child query engine based on a query and index
QueryEngine ()
constructor
virtual ~QueryEngine ()
virtual destructor
Protected Member Functions
virtual QueryEngine * GetEngineFromQuery (std::string query, int index)=0
every derived query engine must return a new instance initialized by a query.
Private Attributes
std::set< QueryEngine * > spawned_children_
Detailed Description
This is a base class that defines the API used by any engine representing an input format.
Definition at line 16 of file query_engine.h.
Constructor & Destructor Documentation
cyclus::QueryEngine::QueryEngine ()
constructor
Definition at line 8 of file query_engine.cc.
References spawned_children_.
cyclus::QueryEngine::~QueryEngine () [virtual]
virtual destructor
Definition at line 13 of file query_engine.cc.
References spawned_children_.
Member Function Documentation
virtual std::string cyclus::QueryEngine::GetElementContent (std::string query, int index = 0) [pure virtual]
investigates the current status and returns a string representing the content of a query at a given index
Parameters:
query the query
index the index of the queried element
Implemented in cyclus::XMLQueryEngine.
Referenced by cyclus::InstModel::AddPrototypeToInitialBuild(), cyclus::GetOptionalQuery(), cyclus::RegionModel::InitAllowedFacilities(), cyclus::InstModel::InitFrom(), cyclus::Model::InitFrom(), cyclus::RegionModel::InitInstitutionNames(), cyclus::XMLFileLoader::LoadControlParams(), cyclus::XMLFlatLoader::LoadInitialAgents(), cyclus::XMLFileLoader::LoadRecipes(), cyclus::XMLFileLoader::LoadSolver(), and cyclus::ReadRecipe().
virtual std::string cyclus::QueryEngine::GetElementName (int index = 0) [pure virtual]
investigates the current status and returns a string representing the name of a given index
Parameters:
index the index of the queried element
Implemented in cyclus::XMLQueryEngine.
Referenced by cyclus::XMLFlatLoader::LoadInitialAgents(), and cyclus::XMLFileLoader::LoadInitialAgents().
virtual QueryEngine* cyclus::QueryEngine::GetEngineFromQuery (std::string query, int index) [protected, pure virtual]
every derived query engine must return a new instance initialized by a query.
Parameters:
query the query
index the index of the queried element
Returns:
a query engine initialized via the snippet
Implemented in cyclus::XMLQueryEngine.
Referenced by QueryElement().
virtual int cyclus::QueryEngine::NElements () [pure virtual]
Returns:
the number of elements in the current query state
Implemented in cyclus::XMLQueryEngine.
virtual int cyclus::QueryEngine::NElementsMatchingQuery (std::string query) [pure virtual]
investigates the current status and returns the number of elements matching a query
Parameters:
query the query
Returns:
the number of elements matching the query
Implemented in cyclus::XMLQueryEngine.
Referenced by cyclus::GetOptionalQuery(), cyclus::RegionModel::InitAllowedFacilities(), cyclus::InstModel::InitFrom(), cyclus::RegionModel::InitInstitutionNames(), cyclus::XMLFileLoader::LoadControlParams(), and cyclus::ReadRecipe().
QueryEngine * cyclus::QueryEngine::QueryElement (std::string query, int index = 0)
populates a child query engine based on a query and index
Parameters:
query the query
index the index of the queried element
Returns:
a initialized query engine based on the query and index
Definition at line 24 of file query_engine.cc.
References GetEngineFromQuery(), and spawned_children_.
Referenced by cyclus::InstModel::InitFrom(), cyclus::RegionModel::InitInstitutionNames(), cyclus::XMLFileLoader::LoadControlParams(), cyclus::XMLFlatLoader::LoadInitialAgents(), cyclus::XMLFileLoader::LoadInitialAgents(), cyclus::XMLFileLoader::LoadRecipes(), cyclus::XMLFileLoader::LoadSolver(), and cyclus::ReadRecipe().
Member Data Documentation
std::set<QueryEngine*> cyclus::QueryEngine::spawned_children_ [private]
Definition at line 73 of file query_engine.h.
Referenced by QueryElement(), QueryEngine(), and ~QueryEngine().
The documentation for this class was generated from the following files:
query_engine.h
query_engine.cc