CYCLUS: cyclus::XMLQueryEngine Class Reference
cyclus::XMLQueryEngine Class Reference
A class for extracting information from a given XML parser.
#include <xml_query_engine.h>
Public Member Functions
virtual std::string GetElementContent (std::string query, int index=0)
investigates the current status and returns a string representing the content of a query at a given index
virtual std::string GetElementName (int index=0)
investigates the current status and returns a string representing the name of a given index
virtual int NElements ()
virtual int NElementsMatchingQuery (std::string query)
investigates the current status and returns the number of elements matching a query
XMLQueryEngine (XMLParser &parser)
constructor given a parser
virtual ~XMLQueryEngine ()
virtual destructor
Protected Member Functions
virtual QueryEngine * GetEngineFromQuery (std::string query, int index)
every derived query engine must return a new instance initialized by a query.
void SetCurrentNode (xmlpp::Node *node)
sets the current node to a given node
XMLQueryEngine (xmlpp::Node *node)
constructor given a node
Private Attributes
xmlpp::Node * current_node_
Detailed Description
A class for extracting information from a given XML parser.
Definition at line 19 of file xml_query_engine.h.
Constructor & Destructor Documentation
cyclus::XMLQueryEngine::XMLQueryEngine (XMLParser & parser)
constructor given a parser
Parameters:
parser the xml parser
Definition at line 12 of file xml_query_engine.cc.
References current_node_, and cyclus::XMLParser::Document().
Referenced by GetEngineFromQuery().
virtual cyclus::XMLQueryEngine::~XMLQueryEngine () [inline, virtual]
virtual destructor
Definition at line 28 of file xml_query_engine.h.
cyclus::XMLQueryEngine::XMLQueryEngine (xmlpp::Node * node) [protected]
constructor given a node
Parameters:
node the node to set as the current node
Definition at line 17 of file xml_query_engine.cc.
References current_node_.
Member Function Documentation
std::string cyclus::XMLQueryEngine::GetElementContent (std::string query, int index = 0) [virtual]
investigates the current status and returns a string representing the content of a query at a given index
Parameters:
query the query
index the index of the queried element
Implements cyclus::QueryEngine.
Definition at line 42 of file xml_query_engine.cc.
References current_node_.
std::string cyclus::XMLQueryEngine::GetElementName (int index = 0) [virtual]
investigates the current status and returns a string representing the name of a given index
Parameters:
index the index of the queried element
Implements cyclus::QueryEngine.
Definition at line 80 of file xml_query_engine.cc.
References current_node_.
QueryEngine * cyclus::XMLQueryEngine::GetEngineFromQuery (std::string query, int index) [protected, virtual]
every derived query engine must return a new instance initialized by a query.
Parameters:
query the query
index the index of the queried element
Returns:
a query engine initialized via the snippet
Implements cyclus::QueryEngine.
Definition at line 99 of file xml_query_engine.cc.
References current_node_, and XMLQueryEngine().
int cyclus::XMLQueryEngine::NElements () [virtual]
Returns:
the number of elements in the current query state
Implements cyclus::QueryEngine.
Definition at line 22 of file xml_query_engine.cc.
References current_node_.
int cyclus::XMLQueryEngine::NElementsMatchingQuery (std::string query) [virtual]
investigates the current status and returns the number of elements matching a query
Parameters:
query the query
Returns:
the number of elements matching the query
Implements cyclus::QueryEngine.
Definition at line 37 of file xml_query_engine.cc.
References current_node_.
Referenced by cyclus::XMLFlatLoader::LoadInitialAgents(), cyclus::XMLFileLoader::LoadInitialAgents(), cyclus::XMLFileLoader::LoadRecipes(), and cyclus::XMLFileLoader::LoadSolver().
void cyclus::XMLQueryEngine::SetCurrentNode (xmlpp::Node * node) [protected]
sets the current node to a given node
Parameters:
node the new current node
Member Data Documentation
xmlpp::Node* cyclus::XMLQueryEngine::current_node_ [private]
Definition at line 82 of file xml_query_engine.h.
Referenced by GetElementContent(), GetElementName(), GetEngineFromQuery(), NElements(), NElementsMatchingQuery(), and XMLQueryEngine().
The documentation for this class was generated from the following files:
xml_query_engine.h
xml_query_engine.cc